### ISSUE TITLE
Wrong Request Method

### ISSUE THREAD

**Issue by csimpi** [LeadDyno/intercooler-js#92]
Hi!

This is my button:
`
<button class="text-danger btn-xs" data-id="1" ic-delete-from="/api/messages/recipients" ic-src="/api/messages/recipients" ic-verb="DELETE" ic-trigger-on="default" ic-deps="ignore" ic-id="1"><i class="fa fa-trash"></i></button>
`

If i click on it, some reason my browser (latest Chrome) use POST Request Method. Why?
I've tried adding `<meta name="intercoolerjs:use-actual-http-method" content="true"/>` but it doesnt works.

**Comment by carsongross** [comment]
We issue all non-GET requests as POSTs with the common metadata for the "actual" HTTP method (the Rails '_method' parameter and the 'X-HTTP-Method-Override' HTTP header) for browser backwards compatibility issues.

If you upgrade to the latest release (0.9.6) and are not concerned with supporting older browsers, there is a way to override this to use the real HTTP method.  Add the following meta-directive to your head tag:

<meta name="intercoolerjs:use-actual-http-method" content="true"/>	

Sorry it's so hacky, but jQuery was issuing DELETEs, etc. at GETs in older browsers, which caused some ugly issues with respect to caching.

**Comment by csimpi** [comment]
I wrote it above, i tried to use that meta tag, but it isnt works. :( The Request method still POST.

**Comment by carsongross** [comment]
Did you upgrade to the latest version?  I released it last Friday, it is very new:

  http://intercoolerjs.org/2016/04/22/intercooler-0.9.6-released.html

Cheers,
Carson

On April 25, 2016 at 8:16:22 AM, csimpi (notifications@github.com) wrote:

I wrote it above, i tried to use that meta tag, but it isnt works. :( The Request method still POST.

**Comment by csimpi** [comment]
If i use
` bower update intercooler-js ` still doesnt works. The latest version is 0.9.5 as i see after bower update.

**Comment by carsongross** [comment]
Ah, darn it, I forgot to push the tag for the release.  Just did.

Can you try updating again?

Cheers,
Carson

On April 25, 2016 at 8:25:51 AM, csimpi (notifications@github.com) wrote:

If i use
bower update intercooler-js still doesnt works. The latest version is 0.9.5 as i see after bower update.

**Comment by csimpi** [comment]
Thanks man, you rock! 
Update ok!
Request Method ok!
Thank for your help and for your time. :+1:

**Comment by carsongross** [comment]
Awesome, glad to hear it’s working properly!

Cheers,
Carson

On April 25, 2016 at 8:49:21 AM, csimpi (notifications@github.com) wrote:

Thanks man, you rock!
Update ok!
Request Method ok!
Thank for your help and for your time.
